
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author evaja
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        jPanel9.setVisible(false);
        pn_menucarro.setVisible(true);
        pn_menuuser.setVisible(false);
        Salir.setVisible(true);
        Date alfofecha = new Date("2000/11/23");
        jugadores.add(new jugador("AlfonsinElFornais", "alfo1234@gmail.com", "Honduras", alfofecha, "alfi123", WIDTH));
        m = (DefaultComboBoxModel) cb_users.getModel();
        m.addElement(new jugador("AlfonsinElFornais", "alfo1234@gmail.com", "Honduras", alfofecha, "alfi123", WIDTH));
        cb_users.setModel(m);
        m = new DefaultComboBoxModel<>();
        m = (DefaultComboBoxModel) cb_pais.getModel();
        m.addElement("Japon");
        m.addElement("Italia");
        m.addElement("USA");
        m.addElement("Alemania");
        m.addElement("Francia");
        m.addElement("UK");
        m.addElement("Sweden");
        cb_pais.setModel(m);

        m = new DefaultComboBoxModel();
        m.addElement("Grupo Q");
        m.addElement("Auto Negocios");
        m.addElement("Auto Excel");

        cb_agregarconc.setModel(m);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pm_vender = new javax.swing.JPopupMenu();
        jm_vender = new javax.swing.JMenuItem();
        jPanel9 = new javax.swing.JPanel();
        pn_iniciosesion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb_users = new javax.swing.JComboBox<>();
        pf_iniciosesion = new javax.swing.JPasswordField();
        bt_iniciarsesion = new javax.swing.JButton();
        bt_registrar = new javax.swing.JButton();
        bt_menucarro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pn_registrar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pf_pswdregistro = new javax.swing.JPasswordField();
        bt_registrarse = new javax.swing.JButton();
        bt_iniciosesion = new javax.swing.JButton();
        bt_menucarro1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nombredeusuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dc_nacimiento = new com.toedter.calendar.JDateChooser();
        tf_correo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_paisdeorigen = new javax.swing.JTextField();
        Salir = new javax.swing.JButton();
        pn_menuuser = new javax.swing.JPanel();
        tp_user = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        bt_comprarcarro = new javax.swing.JButton();
        cb_concesionariacompra = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        l_listarmodificar1 = new javax.swing.JList<>();
        jLabel30 = new javax.swing.JLabel();
        bt_color3 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        tf_precimodificar1 = new javax.swing.JTextField();
        bt_modificar1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        l_eliminar1 = new javax.swing.JList<>();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        cb_concesionaria1 = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        pn_menucarro = new javax.swing.JPanel();
        tp_carro = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cb_pais = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cb_marca = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cb_modelo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        bt_color = new javax.swing.JButton();
        yc_anio = new com.toedter.calendar.JYearChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rb_reconstruido = new javax.swing.JRadioButton();
        rb_agencia = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        cb_agregarconc = new javax.swing.JComboBox<>();
        bt_agregarcarro = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        tf_precio = new javax.swing.JTextField();

        jm_vender.setText("jMenuItem1");
        pm_vender.add(jm_vender);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicio de Sesion: \n");

        pf_iniciosesion.setText("jPasswordField1");
        pf_iniciosesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pf_iniciosesionMouseClicked(evt);
            }
        });

        bt_iniciarsesion.setText("Iniciar Sesion");
        bt_iniciarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_iniciarsesionMouseClicked(evt);
            }
        });

        bt_registrar.setText("Registrarse");
        bt_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarMouseClicked(evt);
            }
        });

        bt_menucarro.setText("Entra como administrador");
        bt_menucarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_menucarroMouseClicked(evt);
            }
        });

        jLabel2.setText("Nombre de Usuario");

        jLabel3.setText("Contraseña");

        jLabel4.setText("O mejor desea: ");

        javax.swing.GroupLayout pn_iniciosesionLayout = new javax.swing.GroupLayout(pn_iniciosesion);
        pn_iniciosesion.setLayout(pn_iniciosesionLayout);
        pn_iniciosesionLayout.setHorizontalGroup(
            pn_iniciosesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_iniciosesionLayout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addGroup(pn_iniciosesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_iniciosesionLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_iniciosesionLayout.createSequentialGroup()
                        .addGroup(pn_iniciosesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_iniciosesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pn_iniciosesionLayout.createSequentialGroup()
                                    .addComponent(bt_registrar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_menucarro))
                                .addComponent(cb_users, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_iniciosesion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_iniciosesionLayout.createSequentialGroup()
                        .addGroup(pn_iniciosesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bt_iniciarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(315, 315, 315))))
        );
        pn_iniciosesionLayout.setVerticalGroup(
            pn_iniciosesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_iniciosesionLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(cb_users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pf_iniciosesion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(bt_iniciarsesion)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_iniciosesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_registrar)
                    .addComponent(bt_menucarro))
                .addGap(82, 82, 82))
        );

        pn_registrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Registrarse");
        pn_registrar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 0, 245, -1));

        pf_pswdregistro.setText("jPasswordField1");
        pn_registrar.add(pf_pswdregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 471, -1));

        bt_registrarse.setText("Registrarse");
        bt_registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarseMouseClicked(evt);
            }
        });
        pn_registrar.add(bt_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 199, 63));

        bt_iniciosesion.setText("Iniciar Sesion");
        bt_iniciosesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_iniciosesionMouseClicked(evt);
            }
        });
        pn_registrar.add(bt_iniciosesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        bt_menucarro1.setText("Entrar como administrador");
        bt_menucarro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_menucarro1MouseClicked(evt);
            }
        });
        pn_registrar.add(bt_menucarro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, -1));

        jLabel6.setText("Nombre de Usuario");
        pn_registrar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 43, 117, -1));

        jLabel7.setText("Correo");
        pn_registrar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 117, 24));

        jLabel8.setText("O mejor desea: ");
        pn_registrar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 100, -1));
        pn_registrar.add(tf_nombredeusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 65, 471, -1));

        jLabel9.setText("Fecha de Nacimiento");
        pn_registrar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 117, 24));
        pn_registrar.add(dc_nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 117, -1));
        pn_registrar.add(tf_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 470, -1));

        jLabel17.setText("Contraseña");
        pn_registrar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 117, 24));

        jLabel18.setText("Pais de Origen");
        pn_registrar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 117, 24));
        pn_registrar.add(tf_paisdeorigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 470, -1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_iniciosesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_iniciosesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 540));

        Salir.setText("Salir\n");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pn_menuuser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_comprarcarro.setText("Comprar");
        jPanel5.add(bt_comprarcarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 250, 30));

        jPanel5.add(cb_concesionariacompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 6, 272, 34));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Año", "Precio"
            }
        ));
        jScrollPane7.setViewportView(jTable1);

        jPanel5.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, 350));

        jLabel21.setText("jLabel21");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 110, -1));

        tp_user.addTab("comprar carro", jPanel5);

        l_listarmodificar1.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(l_listarmodificar1);

        jLabel30.setText("Elija el Color");

        jLabel31.setText("Elija el precio");

        bt_modificar1.setText("Modificar");

        jLabel22.setText("Marca de modificacion:");

        jLabel23.setText("Clasificación:");

        jTextField2.setEditable(false);

        jLabel24.setText("Precio");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(bt_modificar1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_precimodificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_color3)))
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(bt_color3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_precimodificar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(155, 155, 155)))
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(bt_modificar1)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tp_user.addTab("Modificar carro", jPanel6);

        l_eliminar1.setModel(new DefaultListModel()
        );
        jScrollPane5.setViewportView(l_eliminar1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tp_user.addTab("Vender", jPanel7);

        jList2.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(jList2);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                    .addComponent(cb_concesionaria1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(cb_concesionaria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        tp_user.addTab("Listar Carro", jPanel8);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        tp_user.addTab("Modificar usuario", jPanel10);

        pn_menuuser.add(tp_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 780, 490));

        getContentPane().add(pn_menuuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 560));

        pn_menucarro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Pais de Origen: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 25, 190, 32));

        cb_pais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_paisItemStateChanged(evt);
            }
        });
        jPanel1.add(cb_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 67, 126, 47));

        jLabel11.setText("Marcas");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 120, 43, -1));

        cb_marca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_marcaItemStateChanged(evt);
            }
        });
        jPanel1.add(cb_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 148, 126, 47));

        jLabel12.setText("Modelos");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 213, 109, -1));

        jPanel1.add(cb_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 154, 28));

        jLabel13.setText("Color: ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 33, 143, -1));

        bt_color.setBackground(new java.awt.Color(0, 51, 153));
        bt_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_colorMouseClicked(evt);
            }
        });
        jPanel1.add(bt_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 25, -1, 36));
        jPanel1.add(yc_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 67, 72, -1));

        jLabel14.setText("Fecha de Creación: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 67, 172, 35));

        jLabel15.setText("El carro es reconstruido o de agencia:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 286, -1));

        rb_reconstruido.setText("Reconstruido");
        rb_reconstruido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_reconstruidoMouseClicked(evt);
            }
        });
        jPanel1.add(rb_reconstruido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 126, -1));

        rb_agencia.setText("Agencia");
        rb_agencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_agenciaMouseClicked(evt);
            }
        });
        jPanel1.add(rb_agencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 99, -1));

        jLabel16.setText("Concesionaria donde Lo consiguió: ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 243, 19));

        jPanel1.add(cb_agregarconc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 235, 243, 26));

        bt_agregarcarro.setText("Agregar ");
        jPanel1.add(bt_agregarcarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 426, 250, 27));

        jLabel19.setText("Precio:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 206, 40));
        jPanel1.add(tf_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 71, -1));

        tp_carro.addTab("agregar carro", jPanel1);

        pn_menucarro.add(tp_carro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 780, 490));

        getContentPane().add(pn_menucarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarMouseClicked
        pn_iniciosesion.setVisible(false);
        pn_registrar.setVisible(true);
    }//GEN-LAST:event_bt_registrarMouseClicked

    private void pf_iniciosesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_iniciosesionMouseClicked
        pf_iniciosesion.setText("");
    }//GEN-LAST:event_pf_iniciosesionMouseClicked

    private void bt_iniciarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_iniciarsesionMouseClicked
        String pswrd = pf_iniciosesion.getText();
        for (jugador jugadore : jugadores) {
            if (pswrd.equalsIgnoreCase(jugadore.getContraseña())) {
                pn_menuuser.setVisible(true);
                jPanel9.setVisible(false);
                pn_menucarro.setVisible(false);
                Salir.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "La contraseña ingresada es incorrecta");
            }
        }
    }//GEN-LAST:event_bt_iniciarsesionMouseClicked

    private void bt_menucarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_menucarroMouseClicked
        pn_menucarro.setVisible(true);
        pn_menuuser.setVisible(false);
        jPanel9.setVisible(false);
        Salir.setVisible(true);
        DefaultComboBoxModel m = new DefaultComboBoxModel();

        m = (DefaultComboBoxModel) cb_pais.getModel();
        m.addElement("Japon");
        m.addElement("Italia");
        m.addElement("USA");
        m.addElement("Alemania");
        m.addElement("Francia");
        m.addElement("UK");
        m.addElement("Sweden");
        cb_pais.setModel(m);

        m = new DefaultComboBoxModel();
        m.addElement("Grupo Q");
        m.addElement("Auto Negocios");
        m.addElement("Auto Excel");

        cb_agregarconc.setModel(m);
    }//GEN-LAST:event_bt_menucarroMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        jPanel9.setVisible(true);
        pn_registrar.setVisible(false);
        Salir.setVisible(false);
        pn_menucarro.setVisible(false);
        pn_menuuser.setVisible(false);
    }//GEN-LAST:event_SalirMouseClicked

    private void bt_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_colorMouseClicked
        bt_color.setBackground(JColorChooser.showDialog(this, "Agregue el color del carro", Color.yellow));
    }//GEN-LAST:event_bt_colorMouseClicked

    private void rb_reconstruidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_reconstruidoMouseClicked
        rb_agencia.setSelected(false);
    }//GEN-LAST:event_rb_reconstruidoMouseClicked

    private void rb_agenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_agenciaMouseClicked
        rb_reconstruido.setSelected(false);
    }//GEN-LAST:event_rb_agenciaMouseClicked

    private void cb_paisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_paisItemStateChanged
        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_marca.getModel();
        if (evt.getStateChange() == 2) {
            if (cb_pais.getSelectedIndex() == 0) {
                m = new DefaultComboBoxModel();
                m.addElement("Toyota");
                m.addElement("Subaru");
                m.addElement("Honda");
                m.addElement("Mitsubishi");
                m.addElement("Nissan");
                cb_marca.setModel(m);
            } else if (cb_pais.getSelectedIndex() == 1) {
                m = new DefaultComboBoxModel();
                m.addElement("Ferrari");
                m.addElement("Lamborgini");

                cb_marca.setModel(m);
            } else if (cb_pais.getSelectedIndex() == 2) {
                m = new DefaultComboBoxModel();
                m.addElement("Ford");
                m.addElement("Chevrolet");
                m.addElement("ACORH");
                cb_marca.setModel(m);
            } else if (cb_pais.getSelectedIndex() == 3) {
                m = new DefaultComboBoxModel();
                m.addElement("BMW");
                m.addElement("Mercedes-Benz");
                m.addElement("VW");
                m.addElement("Hudi");
                m.addElement("Porsche");
                cb_marca.setModel(m);
            } else if (cb_pais.getSelectedIndex() == 4) {
                m = new DefaultComboBoxModel();
                m.addElement("Deugeot");
                cb_marca.setModel(m);
            } else if (cb_pais.getSelectedIndex() == 5) {
                m = new DefaultComboBoxModel();
                m.addElement("MIM");
                cb_marca.setModel(m);
            }
            if (cb_pais.getSelectedIndex() == 6) {
                m = new DefaultComboBoxModel();
                m.addElement("Sweden");
                cb_marca.setModel(m);
            }
        }
    }//GEN-LAST:event_cb_paisItemStateChanged

    private void cb_marcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_marcaItemStateChanged
        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_modelo.getModel();
        if (evt.getStateChange() == 2) {

        }
    }//GEN-LAST:event_cb_marcaItemStateChanged

    private void bt_iniciosesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_iniciosesionMouseClicked
        pn_iniciosesion.setVisible(true);
        pn_registrar.setVisible(false);
    }//GEN-LAST:event_bt_iniciosesionMouseClicked

    private void bt_menucarro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_menucarro1MouseClicked
        pn_menucarro.setVisible(true);
        pn_menuuser.setVisible(false);
        jPanel9.setVisible(false);
        Salir.setVisible(true);
        DefaultComboBoxModel m = new DefaultComboBoxModel();

        m = (DefaultComboBoxModel) cb_pais.getModel();
        m.addElement("Japon");
        m.addElement("Italia");
        m.addElement("USA");
        m.addElement("Alemania");
        m.addElement("Francia");
        m.addElement("UK");
        m.addElement("Sweden");
        cb_pais.setModel(m);

        m = new DefaultComboBoxModel();
        m.addElement("Grupo Q");
        m.addElement("Auto Negocios");
        m.addElement("Auto Excel");

        cb_agregarconc.setModel(m);
    }//GEN-LAST:event_bt_menucarro1MouseClicked

    private void bt_registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarseMouseClicked
        String name = tf_nombredeusuario.getText();
        String email = tf_correo.getText();
        String country = tf_paisdeorigen.getText();
        Date bd = dc_nacimiento.getDate();
        String pswrd = pf_pswdregistro.getText();

        jugadores.add(new jugador(name, email, country, bd, pswrd, 150000));
        JOptionPane.showMessageDialog(this, "jugador creado");
        m = (DefaultComboBoxModel) cb_users.getModel();
        m.addElement(new jugador(name, pswrd, email, bd, country, 150000));
        pn_registrar.setVisible(false);
        pn_iniciosesion.setVisible(true);
        cb_users.setModel(m);
    }//GEN-LAST:event_bt_registrarseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    ArrayList<jugador> jugadores = new ArrayList<>();
    DefaultComboBoxModel m = new DefaultComboBoxModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JButton bt_agregarcarro;
    private javax.swing.JButton bt_color;
    private javax.swing.JButton bt_color3;
    private javax.swing.JButton bt_comprarcarro;
    private javax.swing.JButton bt_iniciarsesion;
    private javax.swing.JButton bt_iniciosesion;
    private javax.swing.JButton bt_menucarro;
    private javax.swing.JButton bt_menucarro1;
    private javax.swing.JButton bt_modificar1;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JButton bt_registrarse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_agregarconc;
    private javax.swing.JComboBox<String> cb_concesionaria1;
    private javax.swing.JComboBox<String> cb_concesionariacompra;
    private javax.swing.JComboBox<String> cb_marca;
    private javax.swing.JComboBox<String> cb_modelo;
    private javax.swing.JComboBox<String> cb_pais;
    private javax.swing.JComboBox<String> cb_users;
    private com.toedter.calendar.JDateChooser dc_nacimiento;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenuItem jm_vender;
    private javax.swing.JList<String> l_eliminar1;
    private javax.swing.JList<String> l_listarmodificar1;
    private javax.swing.JPasswordField pf_iniciosesion;
    private javax.swing.JPasswordField pf_pswdregistro;
    private javax.swing.JPopupMenu pm_vender;
    private javax.swing.JPanel pn_iniciosesion;
    private javax.swing.JPanel pn_menucarro;
    private javax.swing.JPanel pn_menuuser;
    private javax.swing.JPanel pn_registrar;
    private javax.swing.JRadioButton rb_agencia;
    private javax.swing.JRadioButton rb_reconstruido;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_nombredeusuario;
    private javax.swing.JTextField tf_paisdeorigen;
    private javax.swing.JTextField tf_precimodificar1;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTabbedPane tp_carro;
    private javax.swing.JTabbedPane tp_user;
    private com.toedter.calendar.JYearChooser yc_anio;
    // End of variables declaration//GEN-END:variables
}
